services:
  web:
    container_name: malody-stats-card-web
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3000
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./database:/app/database
      - ./cache:/app/cache
