services:
  web:
    container_name: malody-stats-card-web
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3000
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - malody-database:/app/database
      - malody-cache:/app/cache

volumes:
  malody-database:
  malody-cache:
